import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import FetchNavbar from "@/utils/FetchNavbar";
import Footer from "@/components/Footer/Index";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <FetchNavbar />
        {children}
        <section className="pt-24 lg:pt-28">
          <Footer />
        </section>
        </body>
    </html>
  );
}
